name: manualist

dependencies:
  - python=3.10.9
  - conda-forge::opencv=4.7.0
  - conda-forge::numpy=1.24.2
  - conda-forge::tqdm=4.64.1
  - pytorch::pytorch=1.13.1
  - pip=22.3.1
  - pip:
    - mediapipe==0.9.1.0
    - pafy==0.5.5
    - youtube-dl==2020.12.2
